### ISSUE TITLE
Control messages structure wrong(?)

### ISSUE THREAD

**Issue by heinrich5991** [teeframe/protocol-documentation#1]
> Structure
>
> Control messages have simple structure packet structure. They have a header and payload in the following way:
>
>     byte[0]     // 6bit flags, 2bit ack
>     byte[1]     // 8bit ack
>     byte[2]     // unused - 00
>     byte[3-6]   // security token
>     byte[7]     // message id
>     byte[8-...] // extra data

I believe the security token is at the end of the whole packet, not at the end of the header.

**Comment by miguilimzero** [comment]
@heinrich5991 I just checked here and it seems DDNet has it own security token system which is the one you're describing. I was documenting the 0.6.5 one. Is there any reason for this difference?

**Comment by heinrich5991** [comment]
I designed the 0.6.5 one this way because I thought it'd be the better design. I didn't change DDNet's because of backward compatibility.

**Comment by miguilimzero** [comment]
Well, I also think the 0.6.5 has a better design. I don't even know how to support the security token in the way I'm implementing TeeFrame. 

As far as I can understand, there is no other logical way to find the security token without checking if the packet has an extra 4 bytes at the end (after the first messages with "TKEN").

Do you think a proposal to migrate to the 0.6.5 one would be a good one? By doing the migration, the only breaking change will be that older clients will just connect without the token, the same way as clients connect to older servers.

**Comment by heinrich5991** [comment]
> As far as I can understand, there is no other logical way to find the security token without checking if the packet has an extra 4 bytes at the end (after the first messages with "TKEN").

You can keep track of whether each connection supports the security token, then parse it for these connections only.

> Do you think a proposal to migrate to the 0.6.5 one would be a good one? By doing the migration, the only breaking change will be that older clients will just connect without the token, the same way as clients connect to older servers.

No, I don't think it'd be a good thing. The benefit isn't large enough for a breaking change IMO. Something better would be https://github.com/ddnet/ddnet/pull/6961.

**Comment by miguilimzero** [comment]
> No, I don't think it'd be a good thing. The benefit isn't large enough for a breaking change IMO. Something better would be https://github.com/ddnet/ddnet/pull/6961.

Well, it would be a breaking change that no one will even notice. But I get your point. For now I will comment out everything about security tokens from the documentation, to decide what to do with it later.

**Comment by miguilimzero** [comment]
https://github.com/teeframe/protocol-documentation/commit/a0a2592b2bcf8befff9db725baf608bdf441d053

**Comment by miguilimzero** [comment]
Saving for later https://github.com/teeworlds/teeworlds/commit/a263185571903ead01f6b351a91ea219ac9d215f

**Comment by heinrich5991** [comment]
You probably don't want the 0.6.5 token implementation, it's only supported by the Teeworlds 0.6.5 client.
