### ISSUE TITLE
What is TeeFrame?

### ISSUE THREAD

**Issue by heinrich5991** [teeframe/protocol-documentation#2]
The description says

> The Framework that was missing in the Teeworlds ecosystem. Coming not too soon.

What kind of framework is it? For writing mods?

It also links to https://teeframe.com/, but no server seems to be listening.

**Comment by miguilimzero** [comment]
TeeFram will be a framework for PHP that will APIs to build your TW mod. 

It will provide a base template so you can start your mod implementation with the framework. You will be able to update your mod with the latest changes by just updating the package version and checking the changelogs.

A way to create mods without needing to resolve merge conflicts.

**Comment by miguilimzero** [comment]
It's still in early development. That's why there is no website or anything else about it.

**Comment by heinrich5991** [comment]
Thanks for the explanation. Perhaps you could mention it at https://github.com/teeframe.
